version: '3.9'

networks:
  net:
    driver: bridge

services:
  gms_chroma:
    build:
      context: .
      dockerfile: lib/chroma/Dockerfile
    volumes:
      - ./.cache/chroma:/chroma
      - ./.cache/chroma/index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 5400 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - 8000:8000
    depends_on:
      - gms_clickhouse
    networks:
      - net

  gms_clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./.cache/ch/clickhouse_data:/bitnami/clickhouse
      - ./.cache/ch/backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml
    networks:
      - net

  gms_mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: gmservice
      MONGO_INITDB_ROOT_PASSWORD: gmservice_pass
    ports:
      - 27017:27017
    volumes:
      - ./.cache/mongo/data:/data/db
    networks:
      - net
      
volumes:
  clickhouse_data:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local